### ISSUE TITLE
Support for "mongosh" 

### ISSUE THREAD

**Issue by opensourcegeek** [tpope/vim-dadbod#100]
I was wondering if "mongosh" could be supported may be as a default and if that doesn't exist then fall back to original "mongo" command? I tinkered with the plugin to make use of "mongosh" instead of "mongo" but the returned results aren't getting parsed correctly. It would be great if support for that will be considered in the future.

**Comment by AshMagill** [comment]
in the file:
~/.vim/plugged/vim-dadbod/autoload/db/adapter/mongodb.vim

change everywhere it says 'mongo' to 'mongosh'

could make this easy by using 
:%s/mongo/mongosh/g in vim
hope it works :)

**Comment by tpope** [comment]
In what way does the parsing fail? The parsing for tab completion does not feel like an essential feature.

I don't think I want to open the Pandora's box of supporting multiple clients, but a configuration option to use a different executable wouldn't be out of the question.

**Comment by amenpunk** [comment]
you can change the default cmd in the mongo adapter im ususing packer so my plugins is located in
![image](https://user-images.githubusercontent.com/40347906/174676061-4e5e0d68-f352-4dd0-83bf-f4fb14637e95.png)

this works for me :smile:

**Comment by gidjin** [comment]
FWIW, I installed mongodb community 6.0 and it did not include `mongo` only `mongosh`. I finally ran `brew install mongodb-community@4.4` to install version 4.4 which still included `mongo` at least from the instructions. I'm wondering if they are deprecating it.

**Comment by tpope** [comment]
It's probably time to start transitioning to it as a default. First step:  Figure out what's going wrong with the parsing in `db#adapter#mongodb#tables()`.

**Comment by aldevv** [comment]
I took a look and looks like currently in  mongosh v1.6.0  the output for commands coming through stdin is different compared to the old mongo client:  

**mongo client**
```bash
$ mongo --authenticationDatabase admin -host localhost --port 27017 -u miusuario -p pass --quiet photos <<< "show collections"
```
returns 
```
user_photos
```

**mongosh client**
```bash
$ mongosh --authenticationDatabase admin -host localhost --port 27017 -u miusuario -p pass --quiet photos <<< "show collections"
```
returns
```bash
photos> user_photos
photos> %
```
so this is what is breaking the parsing in `db#adapter#mongodb#tables().`

**Comment by jorgerojas26** [comment]
I need this so badly :( 

i'm using mongodb a lot in my job and this would be super helpful.

Please, someone make a fix :(

I don't have the knowledge to do it myself, sadly.
