### ISSUE TITLE
Support for usernames that  contain the @ symbol

### ISSUE THREAD

**Issue by SaintRyoh** [tpope/vim-dadbod#103]
Hello, I would like to use dadbod to connect to a MSSQL server that has usernames in the format "username@website.com". The connection url doesn't currently seem to support having multiple '@' characters. It looks like the parsing of the url is done on line 44 of url.vim.
`  let match = matchlist(url, scheme . '://\%(\([^@/:]*\):\=\([^@/]*\)@\)\=\(\[[[:xdigit:]:]\+\]\|[^:/;,]*\)\%(:\(\d\+\)\)\=\($\|/.*\)')
`
I don't mind working on this issue and making a pull request, but I'm unsure how/if you'd like to solve it.

thank you!

**Comment by tpope** [comment]
URLs already have a solution for this: `%40`.
