### ISSUE TITLE
Adapter for BigQuery

### ISSUE THREAD

**Issue by mbhynes** [tpope/vim-dadbod#104]
Hi there!

Just wondering whether anyone has ever considered adding an adapter for bigquery?

I see there's a `presto` [adapter](https://github.com/tpope/vim-dadbod/blob/master/autoload/db/adapter/presto.vim), which appears to rely on the `presto` CLI in the environment, which makes me think an equivalent adapter may be possible using the `bq` or `gcloud` CLIs.

- https://cloud.google.com/bigquery/docs/reference/bq-cli-reference
- https://cloud.google.com/sdk/gcloud/

Bigquery has somewhat different configurations than many databases, but can often "autoconfigure" when called via the CLI using env variables or default profiles.

**Comment by tpope** [comment]
[At least one person has considered it.](#95) Nobody has made it past that. I'm no BigQuery expert but `bq` looks like a good fit to me.
