### ISSUE TITLE
Warn about unescaped number sign '#' in URI's password

### ISSUE THREAD

**Issue by ajukraine** [tpope/vim-dadbod#106]
Unfortunately I've got bamboozled by having unescaped '#' character within password. It's just only after 2 hours of digging into source code of vim-dadbod and underlying database tool (sqlcmd), I've figured out what was the cause of the problem.

I think I am not the 1st one fool and not the last one who will spend hours on this. Would be nice to warn user about unescaped unsafe '#' used anywhere else than URI fragment split.

I know it should be fixed somewhere around these lines:

https://github.com/tpope/vim-dadbod/blob/23514a579ce6df28fd956070d9e2ac1051855115/autoload/db/url.vim#L42-L44

But I have some serious PTSD looking at such regexp. But I could try.

**Comment by tpope** [comment]
```
:echo db#url#parse('https://user:pass#word@host')
{'params': {}, 'fragment': 'word@host', 'scheme': 'https', 'opaque': '//user:pass'}
```

I think the giveaway here is an `opaque` value that starts with `//`. An "opaque" URL is one that doesn't conform to the usual `scheme://` conventions, like `mailto:email@example.com`, so an opaque URL that does start with `//` can be used as a signal that something is off.

But I don't think we can stick the warning in `db#url#parse()`.  That method gets called all over the place so you'll end up spamming the message at all sorts of times. I think the warning needs to happen in `:DB` itself.

Also, note that other variations on this mistake, like `https://user#name@host`, *are* valid (if unusual) URLs. The fact we can't catch every mistake makes me wonder if calling out URL escaping in the docs might be a better solution.

**Comment by tpope** [comment]
I just realized there are some edge cases like `sqlite://C:/whatever.sqlite3#anchor` that match my proposed criteria but are technically valid. Let's try the documentation solution.
