### ISSUE TITLE
[Bug] Temporary file not found on macos 

### ISSUE THREAD

**Issue by bogdan** [tpope/vim-dadbod#107]
If nvim is running long enough, the `DB` command stops working with the following error:

![image](https://user-images.githubusercontent.com/122436/164260861-94de6a9a-b126-44e7-9eb9-6bdf0162859a.png)

Using macOS 10.15.5.

Might be similar to https://github.com/tpope/vim-fugitive/issues/1616

**Comment by tpope** [comment]
Yeah that has to be the same issue. I don't think there is much I can do about this. In Fugitive I accommodated by recreating a deleted file, but this looks like the whole directory disappearing, and I don't want to take responsibility for that. Another plugin could possibly mitigate this by touching a temp file once a day, preventing the directory from disappearing to begin with.

My secondary machine is a Mac. I routinely leave Vim running days at a time there untouched and have never seen this issue. That supports my hypothesis that this isn't a standard macOS behavior, although without knowing "long enough", this isn't enough to prove it.

**Comment by bogdan** [comment]
Posting info so that it is searchable by others:

What I end up doing is creating `/etc/periodic.conf.local`

``` sh
#!/bin/sh
# Cleanup tmp files if not accessed for 30 days
daily_clean_tmps_days="30"
```

This makes tmp files cleanup script less agressive.

**Comment by tpope** [comment]
Good hunting, turns out this is stock macOS behavior after all. Looks like these are the defaults, as found in `/etc/defaults/periodic.conf`:

```sh
# 110.clean-tmps
daily_clean_tmps_enable="YES"				# Delete stuff daily
daily_clean_tmps_dirs="/tmp"				# Delete under here
daily_clean_tmps_days="3"				# If not accessed for
daily_clean_tmps_ignore=".X*-lock .X11-unix .ICE-unix .font-unix .XIM-unix"
daily_clean_tmps_ignore="$daily_clean_tmps_ignore quota.user quota.group"
							# Don't delete these
daily_clean_tmps_verbose="YES"				# Mention files deleted
```
