### ISSUE TITLE
Unable to execute statements

### ISSUE THREAD

**Issue by x4121** [tpope/vim-dadbod#11]
Whenever I try to execute a sql statement (with `:{range}DB [url]` or `:DB [url] {cmd}`), I get:

```
Error detected while processing function db#execute_command:
line   66:
E484: Can't open file /tmp/vMjw0en/5.dbout
```
The mentioned file does not exist, only a $i.sql (where $i is the number of the missing file) with the statement to be executed.

Just running `:DB g:bar = mysql:me@myhost` seems to work fine (using the variable later on doesn't).
Connection with the mysql client works fine, executing the statements there as well.

edit: same is happening for PostgreSQL
edit2: also happening inside "clean" ubuntu:artful Docker container with only vim, git, postgresql-client and the plugin installed
edit3: forgot to mention, statement for testing was `:DB mysql://user:password@host.tld/db-name select count(*) from some-table`

**Comment by tpope** [comment]
Check `:echo db#adapter#dispatch("mysql://user:password@host.tld/db-name", "interactive")` and try to run the command it shows you with `:!`.

**Comment by x4121** [comment]
the connection statement generated is correct and works fine.

If I just type `:DB mysql://user:password@host.tld/db-name`, without any query, it connects and starts an interactive session.

**Comment by tpope** [comment]
Might be an issue with the shell redirect then. What is `:set shell?`. Also do you have any funky characters in your password (particularly `!`)?

**Comment by x4121** [comment]
Ah... my shell was set to `sh` because I'm using fish and there is/was some problem with that.
It seems like the plugin has problems with `sh` since it doesn't work with the absolute path as well. Changing the shell to `bash` fixes the issue and the plugin works fine :tada:

**Comment by rike09** [comment]
I'm having the same problem, but in my case I'm using GVim on a Windows machine.
`:set shell?` gives me `shell=C:\Windows\system32\cmd.exe` as would be expected.
Any hint?

**Comment by tpope** [comment]
Can both of you go back to the `v1.0` tag and see if it works then?

**Comment by rike09** [comment]
Going back to `v1.0` gives the exact same error, in a different line, though.

**`v1.0`**
`Error detected while processing function db#escecute_command:
line  66:
E484: Can't open file C:\Users\User\AppData\Local\Temp\VIAB4BD.tmp.dbout`

**`master`**
`Error detected while processing function db#escecute_command:
line  54:
E484: Can't open file C:\Users\User\AppData\Local\Temp\VIo8E12.tmp.dbout`

**Comment by tpope** [comment]
Sounds like your shell settings might be screwed up. What's the output of `:set shell? shellcmdflag? shellpipe? shelltemp? shellquote? shellxquote? shellxescape?`?

**Comment by rike09** [comment]
Here goes the output:

`shell=C:\Windows\system32\cmd.exe`
`shellcmdflag=/c`
`shellpipe=>%s 2>&1`
`shelltemp`
`shellquote=`
`shellxquote=(`
`shellxescape="&|<>()@^`

**Comment by tpope** [comment]
Looks fine. Try to run the command from `:echo db#adapter#dispatch("mysql://user:password@host.tld/db-name", "interactive")` again but this time create an `input.sql` with a SQL query and append `< input.sql > output.log 2>&1`. This should reproduce exactly what `v1.0` does.

**Comment by rike09** [comment]
It worked!
Produced the output.log file with the result of the query in the input.sql file (select count(*) ...):

 count 
-------
   811
(1 row)

**Comment by tpope** [comment]
Okay found one really dumb issue. It should work for `/bin/sh` and `cmd.exe` now. Let me know if it doesn't.

**Comment by rike09** [comment]
It still doesn't work for me...

More details:
I am using postgresql. Echoing the command to be executed in vimscript, I get:

`psql -w "postgresql://user:password@localhost:5432/db" -P columns=120 -v ON_ERROR_STOP=1 -f - < "C:\Users\User\AppData\Local\Temp\VIA4712.tmp.sql" > C:\Users\User\AppData\Local\Temp\VIA4712.tmp.dbout 2>&1`

If I execute this straight in the command line, it works.
If I execute this in vim with :! ... it works.
I couldn't find a way to execute it with :call system(...)

When I execute with :! the shell that pops up shows this:
`C:\Windows\system32\cmd.exe /c (psql -w ^"postgresql://user:password^@localhost:5432/db^" -P columns=120 -v ON_ERROR_STOP=1 -f - ^< ^"C:\Users\User\AppData\Local\Temp\VIA4712.tmp.sql^" ^> C:\Users\User\AppData\Local\Temp\VIA4712.tmp.dbout 2^>^&1)`

Executing `:DB postgresql://user:password^@localhost:5432/db select count(*) from schema.table` still gives the error.

**Comment by tpope** [comment]
The system call is hard to debug. Please try the following:

* Check out v1.0
* Delete lines 1-3 and 5 [here](https://github.com/tpope/vim-dadbod/blob/1dd0e6e0f79e05d0354f680d145f4ac852da15ab/autoload/db.vim#L214-L220), so it always uses the else clause
* Remove the `silent`, so no errors will be hidden behind the scenes

If this works, I'll revert the `system()` approach (which was intended to reduce flicker) until I can get a proper solution in place.

**Comment by rike09** [comment]
Doing what you suggested works. Now I can execute the queries. Thank you!

I noticed another issue with postgres. Example output:

`psql: warning: extra command-line argument "columns=120" ignored`
`psql: warning: extra command-line argument "-v" ignored`
`psql: warning: extra command-line argument "ON_ERROR_STOP=1" ignored`
`psql: warning: extra command-line argument "-f" ignored`
`psql: warning: extra command-line argument "-" ignored`
 `count `
`-------`
`   811`
`(1 row)`

It seems that the url must be the last part of the command, so all the options must come first.
Moving the options next to -w gives no warning (tried in the command line).

**Comment by x4121** [comment]
The current master works fine for me with `set shell=sh`, `v1.0` doesn't
Thanks for all the work :smile: 

PS:
Not sure if that was addressed to me as well, but `:set shell? shellcmdflag? shellpipe? shelltemp? shellquote? shellxquote? shellxescape?` gives
```
  shell=sh
  shellcmdflag=-c
  shellpipe=2>&1| tee
  shelltemp
  shellquote=
  shellxquote=
  shellxescape=
```

**Comment by tpope** [comment]
From `:help system()`.

> Pipes are not used, ...

I think this means using `>` to redirect output in a `system()` call won't work. This seems to reflect the behavior in my Windows VM.  I'm pushing a fix to write the captured output to the file manually instead. This sucks because `system()` itself is writing to a temp file and reading it in, meaning a whole lot of duplicated effort, but at least it works.

I think what's happening with `psql` is it's treating `-P` as a username, throwing the rest of the arguments out of whack. Easy enough to work around.

@rike09 if you could verify both fixes work for you on Windows that would be great. I want to cut a release soon.

**Comment by eloemosynator** [comment]
I can confirm the current master works for me on Windows 10 with Vim 8, I've checked sqlite and postgresql adapters. Thank you, Tim!

**Comment by rike09** [comment]
I can also confirm that it now works for me on Windows 10 and Vim 8, using postgresql adapter.
Thank you very much!
