### ISSUE TITLE
Mongodb queries are treated as sql queries

### ISSUE THREAD

**Issue by AshMagill** [tpope/vim-dadbod#110]
Not so sure this issue belongs here but it is related so I will ask anyway.

When I go into new query with a mongodb url in dadbod-ui and start typing a query out, all of my autocompletion is suggesting that vim is treating the file as sql (and not js), is it possible to set it with a js file extension?

Thanks

for some context:
![pic-full-220605-1917-50](https://user-images.githubusercontent.com/70498054/172043386-edc12dae-c7f2-43a6-b0a6-d21ee6260431.png)

I changed the output in vim-dadbod to text (because it shows linting errors if the extension is json or js), and I was hoping I could change the input extension also (to js), but it didnt seem to do much..

**.vim/plugged/vim-dadbod/autoload/db/adapter/mongodb.vim**

```
function! db#adapter#mongodb#input_extension() abort
  return 'js'
endfunction

function! db#adapter#mongodb#output_extension() abort
  return 'txt'
endfunction
```

**Comment by tpope** [comment]
This is a dadbod-ui question, not dadbod.
