### ISSUE TITLE
Presto adapter fails and needs updating

### ISSUE THREAD

**Issue by morgan-greywolf** [tpope/vim-dadbod#111]
Presto was recently renamed 'trino' and the CLI client is now called that.  Even if you symlink `bin/trino` to `bin/presto`, however, the code in the adapter needs some work as it doesn't even initialize a connection

Doing `:DB presto://trino@localhost:8080/`

results in:

```
E712: Argument of extend() must be a List or Dictionary
```

**Comment by tpope** [comment]
Fixing with the most conservative possible change for now. Long term, we should replace the presto adapter with a trino adapter.
