### ISSUE TITLE
Need help on adding Elasticsearch adapter

### ISSUE THREAD

**Issue by jslim89** [tpope/vim-dadbod#112]
I'm trying to create an [adapter for Elasticsearch](https://github.com/jslim89/vim-dadbod/pull/1/files).

When I run

```
:DB elasticsearch:https://user:pass@my-es-endpoint.com:443 _cat/indices/my_index
```

I get the output

```
{
  "name" : "abc123",
  "cluster_name" : "my-es-cluster",
  "cluster_uuid" : "sd9f8u9808792y387",
  "version" : {
    "number" : "5.6.16",
    "build_hash" : "123456",
    "build_date" : "2021-03-13T15:33:36.565Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

The output didn't take `_cat/indices/my_index` into consideration.

At [this line](https://github.com/jslim89/vim-dadbod/pull/1/files#diff-dbf5d8dd4dae3294986689793950b9ee198b99864b04f42105c1fb9bb3497a9fR20), how can I get the value of `_cat/indices/my_index`

**Comment by tpope** [comment]
You can't. The query is passed on stdin. Dadbod is designed to wrap a database client, not directly interface to to a web API. I'm afraid the best you could do here is write a wrapper script that reads from stdin. Something like this:

```sh
#!/bin/sh
while read line; do
  curl -s -XGET -H'Content-Type: application/json' "$1/$line"
done
```

**Comment by jslim89** [comment]
Thanks for the tips. I will try that.
