### ISSUE TITLE
set and \set does not persist

### ISSUE THREAD

**Issue by kyle-kent** [tpope/vim-dadbod#114]
When running vim dadbod on an ec2 instance to connect to a postgresql db neither the `set` nor `\set` command work.

Sending `set timezone = 'America/Puerto_Rico;' returns a SET response from the db (it worked!). But calling `show timezone;` says nothing has changed.

My workaround at the moment is to send the query along with the `set` command at the same time. eg `set timezone ...; select * from table ...` which works properly. 

Thanks in advance!

**Comment by tpope** [comment]
This is as expected; there is no persistent connection between queries.

You might prefer passing no query to get a long running session in a terminal.

**Comment by kyle-kent** [comment]
Is that functionality in vim dadbod or are you suggesting I use the psql cli?

**Comment by tpope** [comment]
`:DB` with no query argument will start `psql` for you.
