### ISSUE TITLE
Oracle support please

### ISSUE THREAD

**Issue by prabhu-madanagopal** [tpope/vim-dadbod#12]
Is this DB explorer? I could not find any screenshot. Could you please add Oracle support?

**Comment by wspurgin** [comment]
You could add it yourself? The adapters are pretty simple.

**Comment by tpope** [comment]
Yes, even if you don't know VimL, it should be pretty easy to cargo cult a working adapter. I'd do it myself but I don't have half a day to dedicate to getting an Oracle installation working.

**Comment by Adonai** [comment]
@tpope I believe you can take docker image for Oracle XE (like [this](https://hub.docker.com/r/sath89/oracle-12c/) one) for quick start

**Comment by tpope** [comment]
That'll get me a server. How can I get a client?

**Comment by Adonai** [comment]
Here you go: [Oracle Instant Client](http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html).

That's the package containing `sqlplus`, the shell to Oracle database, and ODBC libraries needed to connect.

Last I know you can download these without any form of registration.

**Comment by tpope** [comment]
They require an account, won't allow the email to contain a plus sign, and don't even have a `.deb`. The zip file is just a hodgepodge of files, and the RPM shoves everything in `/usr/lib/oracle/12.2/client64`, meaning I have do a bunch of `ldconfig` and `PATH` bullshit just to get it to run. This is after discovering the first option, "basic client", is not in fact the standard client.

I'll say it again, "I don't have half a day to dedicate to getting an Oracle installation working."

**Comment by Adonai** [comment]
Okay, okay :wink:
I have no intentions of pushing you over the bridge into proprietary abyss.

**Comment by bstaletic** [comment]
Not promising anything, but my work revolves partially around an Oracle DB, so I might try to make an oracle adaptor.

**Comment by tpope** [comment]
Try the `oracle` branch.

**Comment by prabhu-madanagopal** [comment]
:DB oracle://<user>@<sid> 
prompts me for password which is good.
After I enter password, a split window briefly appears and disappears. So I can't tell what the error is.

**Comment by tpope** [comment]
It's probably not a split window but `:silent !sqlplus ...`. You can try [stripping out the `silent`](https://github.com/tpope/vim-dadbod/blob/9188e7b0b647a8fe76d7cef574bc46056c62b6a1/autoload/db.vim#L205), or better, pass a query so the output is captured and loaded into the preview window.

**Comment by prabhu-madanagopal** [comment]
It works closing the ticket. It seems to print the sqlplus output in preview, but I was looking for formatting or browsing the output similar to https://github.com/cosminadrianpopescu/vim-sql-workbench but more lightweight. How can I find out the functions or usage of vim-dadbod? Thanks

**Comment by tpope** [comment]
It's not closed till it's merged.
