### ISSUE TITLE
Feature suggestion SQL Server

### ISSUE THREAD

**Issue by Zethtren** [tpope/vim-dadbod#120]
When running commands in SQL server it is common to use '"' for identifying columns and tables. 

sqlcmd has pretty poor handling of this. 

A good default behaviour is to run "SET QUOTED_IDENTIFIER ON; GO" before the query to allow for normal syntax to be passed.

While most API's and tools seem to do this automatically sqlcmd and consequently dadbod do not.

I will make a suggestion to sqlcmd as well however it would be nice to at least receive a notification that adding this line could help. If an option to auto append is out of the scope. I feel like it might work for dadbod-ui a warning alone would be beneficial here.

Currently I only receive the same output as sqlcmd which is "Syntax error near {spot of first "}"

Again applying this in the scope of this tool may be overkill but it would be a nice feature. If you have other suggestions for who I should recommend this feature to ( In accordance with the tool pipeline involved ) please do let me know!

**Comment by tpope** [comment]
I don't know the first thing about this. Is there a reason a user _wouldn't_ want this?

Looks like the `-I` flag would work, which is a much easier sell than "inject extra commands into the user's query."

**Comment by Zethtren** [comment]
Sorry for the delayed response!

Yeah this is probably fine!

I've since fixed the problem by using the "[]" syntax instead '"' identifiers for SQL Server.

If it's simple and practical to add the option then I would say go for it.

But, I would definitely say that using the "proper" query syntax on my end is probably the better option.

Thank you for looking into it!

**Comment by tpope** [comment]
> But, I would definitely say that using the "proper" query syntax on my end is probably the better option.

Unless/until additional feedback rolls in, I think this is the correct take.
