### ISSUE TITLE
[Feature Request] support filter stderr message

### ISSUE THREAD

**Issue by hiberabyss** [tpope/vim-dadbod#121]
When run sql query, there will be following error message in the output:

```
mysql: [Warning] Using a password on the command line interface can be insecure.
``` 

Is it possible to have option to filter such stderr message?

**Comment by tpope** [comment]
`'errorformat'` can do that.

**Comment by tpope** [comment]
There's no built-in support for this. I supposed you could use a wrapper script, with something like `mysql "$@" 2>&1|grep -v '^mysql: \[Warning'` or whatever to filter it yourself.
