### ISSUE TITLE
connecting to db bdTest: DB exec error: sqlcmd error unkown flag -p in Linux execute sqlcmd

### ISSUE THREAD

**Issue by jockrow** [tpope/vim-dadbod#124]
I'm using
NVIM v0.9.0-dev
Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64) 
        Sep 12 2022 15:07:06 
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 20.04.5 LTS) <X64>  

When I tried to connect to my sqlserver i got this error
connecting to db bdTest: DB exec error: sqlcmd error unkown flag -p

I fixed temporary setting this environment variable with my strong_password: SQLCMDPASSWORD
and edited this file: vim-dadbod/autoload/db/adapter/sqlserver.vim  
replacing this function:
function! db#adapter#sqlserver#interactive(url) abort
  let url = db#url#parse(a:url)
  return ['sqlcmd', '-S', s:server(url)] +
        \ s:boolean_param_flag(url, 'encrypt', '-N') +
        \ s:boolean_param_flag(url, 'trustServerCertificate', '-C') +
        \ (has_key(url, 'user') ? [] : ['-E']) +
        "\ db#url#as_argv(url, '', '', '', '-U ', '-P ', '-d ')
endfunction

for this:
function! db#adapter#sqlserver#interactive(url) abort
  let url = db#url#parse(a:url)
  return ['sqlcmd', '-S', s:server(url)] +
        \ s:boolean_param_flag(url, 'encrypt', '-N') +
        \ s:boolean_param_flag(url, 'trustServerCertificate', '-C') +
        \ (has_key(url, 'user') ? [] : ['-E']) +
		  \ db#url#as_argv(url, '', '', '', '-U ', '', '-d ') "removed -P
endfunction

could be nice to validate this error

**Comment by tpope** [comment]
I don't know what to tell you, [the manual](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16) plainly describes the `-P` option.

**Comment by tpope** [comment]
Fixed by https://github.com/tpope/vim-dadbod/pull/134.
