### ISSUE TITLE
MSSQL password prompt

### ISSUE THREAD

**Issue by ckangnz** [tpope/vim-dadbod#127]
So i have a sql server running in a docker container at port :14333.

I used the connection query : jdbc:sqlserver://localhost:14333;databaseName=default;username=sa;password=password;

But I think the sqlcmd has an update where it doesn't allow you to put in the password in the connection string, but it actually prompts you or wants you to save it as a global variable.

![image](https://user-images.githubusercontent.com/17423698/228519326-9a5bf5c7-4206-4941-8f53-fe81c0361afc.png)

![image](https://user-images.githubusercontent.com/17423698/228519382-7931e0e6-4d96-4b6c-8489-19c0d0e22e7f.png)

![image](https://user-images.githubusercontent.com/17423698/228519440-d70e71d5-9c05-4202-b00d-325f78bcc46c.png)

![image](https://user-images.githubusercontent.com/17423698/228519491-afb89fc2-41a3-42b1-868f-466c86aa5587.png)

Can this plugin ask for password ?

**Comment by tpope** [comment]
I think the fix would be to change [the generated command](https://github.com/tpope/vim-dadbod/blob/389a2b0120f82b13d51ff7c07f5c13f9bc9f412f/autoload/db/adapter/sqlserver.vim#L45-L49) to start with `['env', 'SQLCMDPASSWORD=' . get(url, 'password', ''), ...`.

**Comment by ckangnz** [comment]
hey @tpope, thanks for the response.
I agree that it should use the env variable by default, but shouldn't it also have a way to type in the password by prompt like the error message says?

> The initial passwords must be set using the SQLCMDPASSWORD environment variable or entered at the password prompt

**Comment by tpope** [comment]
No, because it's running in the background and not connected to a terminal. But if it's fixed to use an env var, then Dadbod itself can prompt for the password, achieving largely the same effect.
