### ISSUE TITLE
DB: 'env' executable not found

### ISSUE THREAD

**Issue by MarcoBuess** [tpope/vim-dadbod#146]
Getting above error when trying to connect to a mssql database using `:DB sqlserver://`. `sqlcmd` is available in path. Hints in any direction are highly appreciated. Cheers!

OS: `Windows 10 (10.0.19045)`
Shell: `shell=pwsh.exe`
Editor: `nvim v0.9.1`

**Comment by paultatulea** [comment]
The issue comes from this commit:
https://github.com/tpope/vim-dadbod/commit/15c0832a547d5ef85048a2d709173aab350f0afb

If you restore vim-dadbod to the previous commit, you should be able to connect to your database.

**Comment by tpope** [comment]
Fixing would require adopting the use of the `env` options to `job_start()` and `jobstart()`. As a partial workaround, I've avoided calling `env` if there isn't a password.

**Comment by paultatulea** [comment]
It is working thanks for the quick fix.

**Comment by MarcoBuess** [comment]
Can confirm its working. Tyvm ❤️
