### ISSUE TITLE
Can't connect to LocalDB using sqlserver adapter

### ISSUE THREAD

**Issue by codegax** [tpope/vim-dadbod#150]
Hey guys,
Am trying to connect to to a localdb instance of MS SQL but am failing at it.

Here's what I tried:
`
:echo db#adapter#sqlserver#interactive("sqlserver://\"(LocalDB)\\MSSQLLocalDB\"/DBName)
`
returns: `['sqlcmd', '-S', '"(LocalDB)\\MSSQLLocalDB"', '-E', '-d', 'DBName']` which is the correct order

By removing the `'`,`,`,`[`,`]` and the white space I get this command:
`
sqlcmd -S "(LocalDB)\MSSQLLocalDB" -E -d DBName
`

If I enter that command it gives me connection and let's me query the DB but `:DB sqlserver://\"(LocalDB)\\MSSQLLocalDB\"/DBName` gives me a timeout error.

I also have tried multiple options for the (LocalDB)\MSSQLLocalDB part (like localhost:1443, localhost\sqlexpress, etc) but none with success.
Am I missing some flag or just doing this the wrong way?

**Comment by tpope** [comment]
The first problem I spot is that you shouldn't be including quotes. Those are for the shell (e.g., `cmd.exe`), but Dadbod doesn't use a shell, it runs the command directly.
