### ISSUE TITLE
URL regex/format

### ISSUE THREAD

**Issue by xpegenaute** [tpope/vim-dadbod#158]
Hi,

I miss some documentation about the expected URL format or enough examples about it. Actually. I am trying to develop a new adapter and I need an url like this:

` dbcompanyname://user:password@host:port/userdbname`

I saw that this format is not supported by the [db#url#parse](https://github.com/tpope/vim-dadbod/blob/9d3e3ce74a264642a41e8ae126be5afd095ef107/autoload/db/url.vim#L37) because it went directly to the opaque field. 

I tried to understand your regexp and propose a modification, but sincerely, I had problems following the regexp expression. Probably because vimscrip is not one of my comfort area languages.

Do you know how I can workaround it ? or at least implement it ?

Regards

**Comment by tpope** [comment]
The format is supported fine. But `port` needs to be a number. That's the reason it returns an opaque URL for `db#url#parse('dbcompanyname://user:password@host:port/userdbname')`. Try `db#url#parse('dbcompanyname://user:password@host:1234/userdbname')`.
