### ISSUE TITLE
DB: 'env' executable not found

### ISSUE THREAD

**Issue by TasseDo** [tpope/vim-dadbod#159]
I get the error in title when trying to connect to a SQL Server database using :DB sqlserver:// and the UI, sqlcmd is available in path. 

I've seen the previous issue #146, but I need to use a password in my case so I don't know if I'm missing something obvious or it's normal that it doesn't work?

Any pointers appreciated 

Thanks,

OS: Windows 11
Editor: nvim v0.9.2

**Comment by anish1617** [comment]
I'm stil getting this 'env' executable not found error while connecting to azure sql server. 
Can you please help me if someone has solved this issue.
Appreciate the help.

**Comment by tpope** [comment]
This should be solved for everyone. For vanilla Vi, you'll need 8.2.0239 or newer.

**Comment by anish1617** [comment]
Really Sorry, for not being descriptive. I'm new to vim and this is what i did. 
I'm using neovim and Lazy package manager:
return {
  'tpope/vim-dadbod',
  { 'kristijanhusak/vim-dadbod-completion', ft = { 'sql', 'mssql' } },
  'kristijanhusak/vim-dadbod-ui',
}
And i have Update my plugin from :Lazy
and my connection is as follows:
sqlserver://user1:password123$$$$@some-random-values-45612315d.database.windows.net:1433/customerdb
does having $ character in password needs to be escaped? 

it keeps saying error connecting to db cutomerdb: Db 'env' executable not found.

**Comment by tpope** [comment]
Oh I see, there's a bug. Should be fixed now.
