### ISSUE TITLE
[Windows] DB: 'env' executable not found

### ISSUE THREAD

**Issue by cjhillbrand** [tpope/vim-dadbod#163]
OS: Windows 11
Shell: cmd.exe
nvim: v0.10.0-dev-2400+g8952a89db

It seems I am running into a bit of an issue when trying to provide a URL for my SQL Server hosted in Azure using SQL credentials. The url that I am providing takes the form:
sqlserver://mySqlServer.windows.net:1143;database=MyDatabase;user=myUsername;password=myPassword

I have confirmed that I can connect using sqlcmd by running in cmd.exe
sqlcmd -S mySqlServer.windows.net -d MyDatabase -U myUsername -P myPassword

The one thing that comes to mind is that the password does contain special characters '@' and '#', although looking at the sqlserver.vim adapter I dont see anything that would do anything with these characters. So maybe a deadend thought.

Lastly, to reiterate the title, the message returned from the command is `DB: 'env' executable not found`

Thanks for taking a look, and let me know if there is anything worth trying on my end.

**Comment by tpope** [comment]
This was fixed in #159.
