### ISSUE TITLE
Remove header and footer from SQL PLUS

### ISSUE THREAD

**Issue by nlinaje** [tpope/vim-dadbod#172]
This issue refers to issue [#227](https://github.com/kristijanhusak/vim-dadbod-ui/issues/227) of vim-dadbod-ui plugin.
Depending on the SQLPlus version, we get different amount of lines for header/footer. This makes it difficult to remove them, as it depends on the SQL Plus version.

The oracle adapter in vim-dadbod plugin calls the tool as `sqlplus -L`. The solution is to remove the header and footer with `sqlplus -L -S`. In this case, the output data is equal for all tested versions.

In the code, instead of:
`return [get(g:, 'dbext_default_ORA_bin', 'sqlplus'), '-L',`
change to:
`return [get(g:, 'dbext_default_ORA_bin', 'sqlplus'), '-L', '-S',`

Thx a log for this amazing plugin!

Note: This is my first time opening an issue. Should I do a pull request? I don't know yet how it works :(

**Comment by dbmatheus** [comment]
Hi @nlinaje, I was also looking into this issue and found out in the vim-dadbod plugin there's an option already implemented but I'm not sure how this could be done from vim-dadbod-ui (I'm pretty new to nvim/vimscript).

The oracle.vim have this piece of code which uses -S option to sqlplus:
`function! db#adapter#oracle#filter(url) abort
  let cmd = db#adapter#oracle#interactive(a:url)
  call insert(cmd, '-S', 1)
  return cmd
endfunction
`

**Comment by nlinaje** [comment]
A solution has been found inside vim-dadbod-ui. No changes in this project needed.
