### ISSUE TITLE
SQL Server: executable not found

### ISSUE THREAD

**Issue by marazza-dev** [tpope/vim-dadbod#176]
Hello, first of all thank you for the amazing work!
It looks like since [this commit](https://github.com/tpope/vim-dadbod/commit/7fb9ea743275861eb5bc6f31ae48086f51720960) I cannot get a connection with sql server, before that I had no issues.

sqlcmd is available and connects me to the db with the same connection string.

My connection string: `sqlserver://User:pass-123-!@sql.database.windows.net:1433/dbname`

This is the command output:

```txt
['env', 'SQLCMDPASSWORD=pass-123-!', 'sqlcmd', '-S', 'sql.database.windows.net,1433', '-U', 'User', '-d', 'dbname']
```

Thank you in advance

**Comment by kristijanhusak** [comment]
Similar thing reported here https://github.com/kristijanhusak/vim-dadbod-ui/issues/247
