### ISSUE TITLE
E605: Exception not caught: DB: no adapter for postgre

### ISSUE THREAD

**Issue by yakiza** [tpope/vim-dadbod#182]
After Instaling dadod with lazy and launching the DBUI, proceding to Adding New Connection to my postgresql db I get the following error:

> E605: Exception not caught: DB: no adapter for postgre

The connection link looks like this postgres://postgres:{my password}@localhost:5432/mydb 
I have verified via netstat that the database is indeed running on the port 5432,

My configuration is the one provided on the github by TJ 

`return {
  'kristijanhusak/vim-dadbod-ui',
  dependencies = {
    { 'tpope/vim-dadbod', lazy = true },
    { 'kristijanhusak/vim-dadbod-completion', ft = { 'sql', 'mysql', 'plsql' }, lazy = true }, -- Optional
  },
  cmd = {
    'DBUI',
    'DBUIToggle',
    'DBUIAddConnection',
    'DBUIFindBuffer',
  },
  init = function()
    -- Your DBUI configuration
    vim.g.db_ui_use_nerd_fonts = 1
  end,
}`

**Comment by tpope** [comment]
`postgre`? You have a typo.
