### ISSUE TITLE
Can't get vim-dadbod to work with vim-dotenv

### ISSUE THREAD

**Issue by dunk** [tpope/vim-dadbod#20]
I must be doing something horribly wrong. I have a file in the root of my repo called `.env`with a single line in it:
```
DATABASE_URL='mysql://db_user:db_pass@some.host/some_db'
```
I'm opening vim in that folder, and executing `:Dotenv` shows this env var. However, executing a bare `:DB select 1` results in "DB: no URL" and executing`:DB $DATABASE_URL select 1` results in "DB: no adapter for file /path/to/current/dir/$DATABASE_URL".

Am I doing this dumb or is it a bug?

**Comment by tpope** [comment]
This is a bug in dotenv. It's showing you the environment for the current working directory, but it should be showing you nothing, because you don't have a file open. Open a file and it will do what you expect.

Feel free to submit an issue (or better yet, a PR) to the dotenv repository.
