### ISSUE TITLE
Unable to connect to MongoDB that requires authentication and SSL

### ISSUE THREAD

**Issue by oolongtea** [tpope/vim-dadbod#21]
Executing the following
```
:DB mongodb://user@mymongo.com:9011/mydb
```
results in the error
```
2018-03-15T11:03:38.728-0400 I NETWORK  [thread1] Socket recv() Connection reset by peer 1.2.3.4:9011
2018-03-15T11:03:38.728-0400 I NETWORK  [thread1] SocketException: remote: (NONE):0 error: 9001 socket exception [RECV_ERROR] server [1.2.3.4:9011] 
2018-03-15T11:03:38.728-0400 E QUERY    [thread1] Error: network error while attempting to run command 'isMaster' on host 'mymongo.com:9011'  :
connect@src/mongo/shell/mongo.js:240:13
@(connect):1:21
exception: connect failed
Press ENTER or type command to continue
```

Looking further with this shows the exact command being run:
```
:echo db#adapter#dispatch("mongodb://user@mymongo.com:9011/mydb", "interactive")
```
```
mongo --host 'mymongo.com' --port '9011' -u 'user' 'mydb'
```
which does not work in another terminal.

The expected command and flags that do work are:
```
mongo --host 'mymongo.com' --port '9011' -u 'user' 'mydb' -p --ssl
```

What would be the best way to add these flags? Is there a function in the mongo adapter where I can append this or customize it?

I'm using mongodb shell v3.4.13, NVIM v0.2.3-455-gbc17ad3, and vim-db (when it was named that) as of commit hash 7e57e5a75bbec6d909f544465ae1e899d6ec3b15.

**Comment by tpope** [comment]
Yuck, how does a database this new not auto-negotiate?

You'll need to update the MongoDB adapter's `#interactive()` to explicitly `db#url#parse()` the passed in URL, and append `--ssl` if `get(url.params, 'ssl')` is true. Then you can call `mongodb://user@mymongo.com:9011/mydb?ssl=true`. Take a stab at a PR and I can offer further guidance.
