### ISSUE TITLE
Preview window with query result is modifiable (Windows)

### ISSUE THREAD

**Issue by eloemosynator** [tpope/vim-dadbod#25]
Environment:

Windows 10, vim 8.0, latest vim-dadbod

Preview window with query results is not read-only, I can modify the buffer contents, the data is not wrapped, I can list the buffer using 'ls'  - it looks like s:init() function never gets executed.
Tested it with postgres and sqlite3 adapters (I don't think it's specific to any adapter though).

The same vim-dadbod behaves as expected on FreeBSD 10 with vim 8.0, so it looks like a Windows-specific issue.

**Comment by tpope** [comment]
Good detective work. Can you tell me what `:echo fnameescape(tempname())` looks like?

**Comment by tpope** [comment]
I'm guessing something in the spirit of https://github.com/tpope/vim-fugitive/commit/4f24757df2a57fc01900334114b1790fcb75ad54 will fix it.

**Comment by eloemosynator** [comment]
Ok, I've tried the "spirit of vim-fugitive" :) didn't work.
Spend some time researching (sadly, I'm not vimscript expert).
This fixed it for me (replaced backslash with forward slash in the output file name), here's the unified diff for db.vim (sorry for being old-fashioned and not doing git pull-request voodoo, don't have git on my win box):

```
@@ -231,7 +231,7 @@
         call writefile(lines, infile)
       endif
       call s:filter_write(conn, infile, outfile)
-      execute 'autocmd BufReadPost' fnameescape(outfile)
+      execute 'autocmd BufReadPost' substitute(fnameescape(outfile), '\', '/', 'g')
             \ 'let b:db_input =' string(infile)
             \ '| let b:db =' string(conn)
             \ '| let w:db = b:db'
```

**Comment by eloemosynator** [comment]
Almost forgot - obviously, "substitute" needs to we wrapped in "if has('win32')" block.

**Comment by tpope** [comment]
Looks pretty safe. Not too worried about backslashes in `tempname()` on UNIX.
