### ISSUE TITLE
Background execution

### ISSUE THREAD

**Issue by jerri** [tpope/vim-dadbod#27]
Is there a chance to get some asynchronous background execution? I am using this with a database that takes quite long to answer on requests, so this disrupts me quite a lot at the moment.
Maybe I should just use an additional terminal window for this, but I think it would be an awesome addition, no?
Thanks in any case for this plugin.

**Comment by tpope** [comment]
I started writing this plugin before Vim 8.0 and the job API shipped, but now that that's available I would certainly like to. If you're waiting on me to do it you may be waiting a while.

**Comment by jerri** [comment]
Thanks for the feedback. Mhm... Not sure if I am up to it, though. So I will have to wait I think. :-)
