### ISSUE TITLE
Execute query under cursor

### ISSUE THREAD

**Issue by lackac** [tpope/vim-dadbod#33]
I was making a lot of use of `vim-dadbod` in recent weeks. One thing that I was missing was the ability to run the query under the cursor. I ended up creating a _query text object_ to help me do just that. It is implemented like this:

```vim
" sql query text object
vnoremap aq <esc>:call search(";", "cWz")<cr>:call search(";\\<bar>\\%^", "bsWz")<cr>:call search("\\v\\c^(select<bar>with<bar>insert<bar>update<bar>delete<bar>create)\>", "Wz")<cr>vg`'
omap aq :normal vaq<cr>
```

It searches backward for the last `;` character or the beginning of the file and then from there forward for the next SQL keyword (I'm sure the list there might be refined, this worked for me though). It switches to visual mode and searches for the next `;` character.

Then I mapped `<C-Q>` to execute the query using `b:db` as the database url:

```vim
" setup b:db and run queries with it
nmap <expr> <c-q> exists("b:db") ? 'vaq:DB b:db<cr>' : ':DB b:db = g:db_'
vmap <expr> <c-q> exists("b:db") ? ':DB b:db<cr>' : '<esc>:DB b:db = g:db_'
```

The conditional expression checks first whether `b:db` is set. It starts a command line expression to set it based on a `g:db_*` variable if it's not. We could throw an error instead here.

Would it make sense to add this to dadbod?

**Comment by lackac** [comment]
All of that makes sense. I'm also starting to get annoyed by the prompt.

I'm closing this now as it looks like there's no action to take on it here.

**Comment by oliverralbertini** [comment]
I was trying to map `<c-c><c-c>` since I've gotten used to using slime recently, but couldn't get it to work.

I ended up using

```
autocmd FileType sql xmap <expr> <C-M> db#op_exec()
```

By making each query it's own paragraph, running queries is `vip<enter>`

**Comment by willruggiano** [comment]
@oliverralbertini I love it, but it's a lil magic to me and I can't find anything on <C-M>. Care to briefly explain how that mapping is working when `vip<enter>`?

**Comment by oliverralbertini** [comment]
@willruggiano The mapping translates as: for SQL files map "enter" to run the selected query in visual mode.

The `vip` part is a convenient way to enter visual mode with the paragraph under the cursor selected. If you organize your code into paragraphs it's easy to navigate among them (`{` and `}`) and then run the query under cursor.
