### ISSUE TITLE
PostgreSQL Transactions

### ISSUE THREAD

**Issue by forbesmyester** [tpope/vim-dadbod#40]
It seems PostgreSQL transactions don't work at all.

A simple test case would be:

    :DB begin
    :DB rollback

which results in:

    psql:<stdin>:1: WARNING:  there is no transaction in progress
    ROLLBACK

I don't know if this is out-of-scope for dadbod, but a good few of my use cases are impossible without this working.

With or without, I still love this for vim plugin and still use it every day, so thanks for your work.

**Comment by tpope** [comment]
Currently out of scope, as each DB query spawns a new connection. I started working on Dadbod a bit before the job interface came out.

**Comment by forbesmyester** [comment]
No problem, thanks for your work on this, as I still use it a hell of a lot and the frustration I feel when I need transactions is only a reflection of how much I like using dadbod when  I don't!

Thanks for your great work on this and your other mods.
