### ISSUE TITLE
Document additional adapters implementations

### ISSUE THREAD

**Issue by hauleth** [tpope/vim-dadbod#42]

**Comment by PeteW** [comment]
+1 I'd like to contribute an ODBC adapter for those of us that need to use less common database interfaces.

**Comment by tpope** [comment]
Copy and paste the MySQL adapter, make the hopefully self evident necessary changes, ask if you have questions!

**Comment by tpope** [comment]
Oh, and the SQL Server adapter is sort of like a special case ODBC handler, take a look at that one too.
