### ISSUE TITLE
Using .mylogin.cnf for a mysql connection

### ISSUE THREAD

**Issue by trallarn** [tpope/vim-dadbod#45]
First of all, thanks for the great work with this plugin!

In order to use encrypted password for a mysql connection I'm using .mylogin.cnf. To use a connection from this configuration file from the shell I would use
`mysql --login-path=<entry-in-config>`

Is there any way to supply the `login-path` flag using dadbod?

Thanks!

**Comment by tpope** [comment]
Not currently supported. Is there a way to check if `<entry-in-config>` actually exists in the config? I think it might make sense for `mysql:<entry-in-config>` to work if it's there, but fallback to treating it as a hostname if not.

**Comment by trallarn** [comment]
That sounds like a good approach.

An entry in `.mylogin.cnf` does not contain the actual database so if possible it would be nice if dadbod would still extract that from the url, like so `mysql:<entry-in-config>/<database>`.

This is how one can check if an entry exists in the config:

```
$ mysql_config_editor print --login-path test
[test]
user = test-user
password = *****
host = test
```

**Comment by tpope** [comment]
Eh that's a bit less intuitive, going for a query param for now because that's easy to implement.
