### ISSUE TITLE
Reuse connection

### ISSUE THREAD

**Issue by LukeMauldin** [tpope/vim-dadbod#46]
Is there a way to get the mongo driver adapter to reuse the mongo connection rather than establishing a new connection each time?

**Comment by tpope** [comment]
Unfortunately there isn't really a connection to speak of, just an ephemeral `mongo` CLI invocation. Even if we kept it running, I don't think there would be a clean way to send it multiple statements and receive multiple results. We'd probably need a real TCP based connection using Vim channels for that.
