### ISSUE TITLE
ODBC support via isql

### ISSUE THREAD

**Issue by mebaran** [tpope/vim-dadbod#52]
I'm not very good at vimscript, but would it be possible to add support for isql from unixodbc?  Some of the more proprietary databases have only ODBC drivers, so it would open up a huge world of connectivity (they all seem to work with unixodbc).

**Comment by tpope** [comment]
I tried to use `isql` for SQL Server and found it to be largely broken and abandoned. Perhaps you'll have more luck with a different database. If you get it to work from the command line, wrapping it for Dadbod shouldn't be too hard.
