### ISSUE TITLE
Ensure arguments which enable non-wrapping multi-line output are passed when calling database CLIs

### ISSUE THREAD

**Issue by AlexisGoodfellow** [tpope/vim-dadbod#53]
Wrapped output on a terminal screen is very hard to comprehend when querying most realistic production databases, where single fields that can be 200+ characters long. This is really poor UX and makes it really hard to figure out if code that I've written to interact with databases is actually doing the right thing.

I'd be very surprised if database CLI designers haven't thought of this. Where possible, I'd like to see if there are command line options which can be enabled when starting up an interactive shell into the database, and see if these options can be automatically turned on by default through dadbod when they are available. 

Thanks for all your hard work, Tim!

**Comment by tpope** [comment]
> I'd be very surprised if database CLI designers haven't thought of this.

Well yes, I think they *have* thought of this, and factored this in when picking their defaults. I don't want to get into the business of bikeshedding their decisions.

If you have actual options you want to set, you're probably better off setting them somewhere like `.psqlrc` or `.my.cnf` anyways, so you can benefit from them outside of Vim as well as in it.
