### ISSUE TITLE
Pass buffer/selection through other command first?

### ISSUE THREAD

**Issue by sdressler** [tpope/vim-dadbod#58]
This is more a question than an issue: I wonder whether it would be possible to pass the buffer/selection to be send to the DB via an additional filter or extending command. For example, if I have

    SELECT COUNT(*)
    FROM foo;

and execute this in e.g. PostgreSQL, then it would be very efficient to get the EXPLAIN or EXPLAIN ANALYZE output by e.g.

    %DB | echo "EXPLAIN ANALYZE" | postgresql://postgres@localhost/mydb

Or a similar sequence.

My assumption: this already works out of the box and I am just not googling for the right thing. Happy about any help.

**Comment by tpope** [comment]
Vim doesn't have anything resembling pipes. `:%DB postgres://... foo` currently ignores the `foo`; it would probably be pretty easy to prepend it to the query if that's an adequate solution.

**Comment by sdressler** [comment]
Thanks for the answer! Prepending would be absolutely acceptable. I just want to avoid having to change the query in the buffer and then reverting the change.
