### ISSUE TITLE
Infinite loop while resolving URL if it contains an octothorp

### ISSUE THREAD

**Issue by evanthegrayt** [tpope/vim-dadbod#59]
If the URL contains an octothorp (`#`), the plugin throws `DB: infinite loop resolving URL`. To recreate: 
```
:DB postgres://user:pas#word@db/mydb
```
I've tried various ways of quoting/escaping the octothorp, to no avail. Surely I'm missing something because I'd assume they're common in passwords?

Any help would be appreciated. 

Big fan of your work, by the way; thanks for so many awesome plugins.

**Comment by tpope** [comment]
`%23`
