### ISSUE TITLE
preview window wrapping when using autocmd to execute '%DB'

### ISSUE THREAD

**Issue by kristijanhusak** [tpope/vim-dadbod#60]
I have this strange bug that i can't figure out.

I set up an autocmd for my *.sql files to automatically execute when i write them:
```
autocmd BufWritePost *.sql exe '%DB'
```
When i write a file, preview .dbout has `set wrap` set.
When i execute `:%DB` manually, it is properly set to `nowrap`.

This doesn't happen when i set `nowrap` globally, but i'm not setting it at all, and it defaults to `wrap`. in that case.

Do you have an idea what can be the issue? Thanks!

**Comment by tpope** [comment]
`:help autocmd-nested`

**Comment by kristijanhusak** [comment]
That does the trick, thanks!
