### ISSUE TITLE
postgres table completion hangs (vim, win10)

### ISSUE THREAD

**Issue by habamax** [tpope/vim-dadbod#61]
vim 8.2.444, postgres 10.12, win10 

When I issue a command:

     DB postgres://postgres:@localhost:5432/postgres <tab>

I get cmd window opened that does nothing:

```
C:\WINDOWS\system32\cmd.exe /c (^(psql -w -P columns=146 -v ON_ERROR_STOP=1 -f - ^"postgresql://postgres^@localhost:5432/postgres^" --no-psqlrc -tA -c ^"\dtvm^"^) ^>C:\Users\maksim.kim\AppData\Local\Temp\VIoFE4B.tmp 2^>^&1)
```

PS on neovim it shows 3 dots and nothing happens then.

PPS regular queries works:

     DB postgres://postgres:@localhost:5432/postgres select * from test

returns select data.

**Comment by tpope** [comment]
Can you try running that `psql` command and see what it does? I'm guessing you will have to remove the `^` escapes.

**Comment by habamax** [comment]
I have removed `^` and run:

```
C:\Users\maksim.kim>C:\WINDOWS\system32\cmd.exe /c ((psql -w -P columns=146 -v ON_ERROR_STOP=1 -f - "postgresql://postgres@localhost:5432/postgres" --no-psqlrc -tA -c "\dtvm") >C:\Users\maksim.kim\AppData\Local\Temp\VIoFE4B.tmp 2>&1)
```

Still no response (had to kill with Ctrl-c)

**Comment by habamax** [comment]
If I change double quotes of db name to single quotes:

```
C:\Users\maksim.kim>C:\WINDOWS\system32\cmd.exe /c (^(psql -w -P columns=146 -v ON_ERROR_STOP=1 -f - 'postgresql://postgres^@localhost:5432/postgres' --no-psqlrc -tA -c ^"\dtvm^"^) ^>C:\Users\maksim.kim\AppData\Local\Temp\VIoFE4B.tmp 2^>^&1)
```

It looks like it work, well, I mean it doesn't hang.

But no tables are returned

**Comment by habamax** [comment]
The log is (translated to eng):

```
psql: warning: extra(redundant?) argument "-tA" was ignored
psql: warning: extra(redundant?) argument  "-c" was ignored
psql: warning: extra(redundant?) argument  "\dtvm" was ignored
psql: FATAL:  role "--no-psqlrc" does not exist
```

**Comment by habamax** [comment]
I can get list of tables with this psql:

![image](https://user-images.githubusercontent.com/234774/77990455-110b5f00-732a-11ea-8397-38442c810b6a.png)

**Comment by habamax** [comment]
Now interesting thing:

this works

```
C:\Users\maksim.kim>psql -w -P columns=146 -v ON_ERROR_STOP=1 --dbname="postgresql://postgres@localhost:5432/postgres" --no-psqlrc -tA -c "\dtvm"
public|hello|ЄрсышЎр|postgres
public|test|ЄрсышЎр|postgres
```

and this (adding `-f`) doesn't:

```
C:\Users\maksim.kim>psql -w -P columns=146 -v ON_ERROR_STOP=1 -f --dbname="postgresql://postgres@localhost:5432/postgres" --no-psqlrc -tA -c "\dtvm"
psql: FATAL:  role "maksim.kim" does not exist
```

**Comment by tpope** [comment]
Removing the `^` was meant to account for the fact `cmd /c` was also being removed. You should do both or neither.

Single quotes aren't supported on Windows, unless psql is doing something weird.

**Comment by habamax** [comment]
> Removing the `^` was meant to account for the fact `cmd /c` was also being removed. You should do both or neither.


![image](https://user-images.githubusercontent.com/234774/78105544-13d58500-73fa-11ea-8bce-8643d3ae2f96.png)

```
psql: warning: redundant argument "-tA" is ignored
psql: warning: redundant argument "-c" is ignored
psql: warning: redundant argument "\dtvm" is ignored
```

I have tried to put `\dtvm` into `test.sql` file and provide it to `-f` instead of `-`:

![image](https://user-images.githubusercontent.com/234774/78105905-eccb8300-73fa-11ea-986c-c06c59126634.png)

And it works. Not sure how `-` should work here.


> Single quotes aren't supported on Windows, unless psql is doing something weird.

Indeed, my bad.
