### ISSUE TITLE
DB connection via URI does not work when password contains @ symbols

### ISSUE THREAD

**Issue by bew** [tpope/vim-dadbod#74]
TSIA

I have a DB URI that looks like:
`postgresql://user:p@ssword@hostname/db_name`

The connector seems to take the password up to the first `@` (`p`) and the hostname is then `ssword@hostname` instead of just `hostname`

**Comment by Rom1deTroyes** [comment]
See #72 and #1 :

> From RFC 1738:
> 
> > The user name (and password), if present, are followed by a
> > commercial at-sign "@". Within the user and password field, any ":",
> > "@", or "/" must be encoded.
> 
> The `@` character is URL encoded as `%40`.

**Comment by bew** [comment]
My bad, thank you
