### ISSUE TITLE
Google Big Query adapter

### ISSUE THREAD

**Issue by gviamont** [tpope/vim-dadbod#79]
Hi Tim, I noticed in #69 that there was brief discussion about adding a Big Query adapter.  Correct me if I'm wrong, but it doesn't look like the author of the issue ended up contributing a PR with such an adapter.  I have some interest in adding one to vim-dadbod and wanted to see if you might consider taking a look at a contributed PR for one.

Roughly in terms of design I was thinking of wrapping the gcloud command line utility [bq](https://cloud.google.com/bigquery/docs/bq-command-line-tool) much like you have done with the mysql and psql command line utilities for MySQL and PostgreSQL, respectively.  Is this something you'd consider accepting a PR for, and does this seem like a sensible approach?

**Comment by tpope** [comment]
Yes, that seems reasonable, and those 2 adapters are a good starting point. Make sure you're on the latest `master`, as there has been some very recent retooling.
