### ISSUE TITLE
mysql:[Warning]

### ISSUE THREAD

**Issue by MarkBassett** [tpope/vim-dadbod#81]
Query results show
mysql: [Warning] Using a password on the command line interface can be insecure.
+---- 12 lines: +----------------------------------------
even though command is executed, results are not shown?
If I yank the lines and paste results are shown.
mysql: [Warning] Using a password on the command line interface can be insecure.
+--------------------+
| Database           |
+--------------------+
| book_shop          |
| cat_app            |
| information_schema |
| mysql              |
| pastery_app        |
| performance_schema |
| shirts_db          |
| sys                |
+--------------------+

**Comment by tpope** [comment]
I don't understand. If no results are shown, then what are you yanking?

**Comment by MarkBassett** [comment]
Fair point, attached is a screenshot of what I get back.If I yank line 2, I get.
+--------------------+
| Database           |
+--------------------+
| book_shop          |
| cat_app            |
| information_schema |
| mysql              |
| pastery_app        |
| performance_schema |
| shirts_db          |
| sys                |
+--------------------+

![Screenshot 2021-01-16 at 09 48 23](https://user-images.githubusercontent.com/6088456/104808740-29c50280-57e0-11eb-98dd-7bfe6b060596.png)

**Comment by tpope** [comment]
Looks like it's folded. Try pressing `zR` to open it, and check `:verbose set foldmethod?` to see the name of the VimL file that enabled folding.

**Comment by MarkBassett** [comment]
That worked, love your plugins by the way, currently using 8 on them. Thanks for your help, much appreciated.
