### ISSUE TITLE
PostgreSQL host is wrongly encoded when using socket directory

### ISSUE THREAD

**Issue by hauleth** [tpope/vim-dadbod#91]
I am trying to connect to the DB using:

```
:DB postgres:///langusta_dev?host=%2FUsers%2Fhauleth%2FWorkspace%2Fhauleth%2Flangusta%2F.direnv%2Fpostgres&user=postgres&password=postgres&application_name=langusta
```

And it fails with:

```
psql: error: could not translate host name "\/Users\/hauleth\/Workspace\/hauleth\/langusta\/.direnv\/postgres" to address: nodename nor servname provided, or not known
```

If I remove `host` option (`PGHOST` option is set to the same value) then it properly connect.

**Comment by tpope** [comment]
Does `psql <your-url>` work at the command line?

**Comment by hauleth** [comment]
@tpope nevermind. It was bug in my implementation of `:Start`. I am using NeoVim and it was implemented as (rough equivalent):

```viml
<mods>new
call termopen(map(<f-args>, escape))
startinsert
```

But additional quotes around URI are screwing such straightforward implementation.

**Comment by tpope** [comment]
The argument Dadbod passes to `:Start` is a shell command, so you probably want `call termopen(<q-args>)`.

**Comment by hauleth** [comment]
@tpope indeed. Sorry for bothering you with the issue.
