### ISSUE TITLE
Error detected while processing function <SNR>46_init:

### ISSUE THREAD

**Issue by pkail** [tpope/vim-dadbod#93]
When I run a query using :%DB I get an error:

Error detected while processing function <SNR>46_init:
line    5:
E119: Not enough arguments for function: bufnr

If I press Enter the query runs OK.
Running PG on localhost.

**Comment by tpope** [comment]
I'll fix this regardless, but can you tell me what Vim version this is happening on?

**Comment by pkail** [comment]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 13 2020 15:49:09)
Included patches: 1-1453
