### ISSUE TITLE
dadbod not executing queries

### ISSUE THREAD

**Issue by SamuelTheJackson** [tpope/vim-dadbod#94]
I'm usin vim-dadbod and vim-dadbod-ui with neovim 0.5.

I'm using the following `mysql` script:
```bash
#!/bin/bash
NAME="duahnsadfjuqaaaasdjf"
if [ ! "$(docker ps -q -f name=$NAME)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=$NAME)" ]; then
        docker rm $NAME
    fi
    docker run --network dev-network --name $NAME -itd -e MYSQL_ALLOW_EMPTY_PASSWORD=true -v /tmp:/tmp mysql:8.0.17 &
fi

echo "$@" >> /tmp/test.mysql

docker exec $NAME mysql "$@"
```

I add the following connection:
`mysql://user:password@mysql:3306/database`
This works and the ui shows me all tables. The `/tmp/test.mysql` file shows me that `-h mysql -P 3306 -u user -ppassword database -e show tables` gets executed.

When I try to execute a `select` statement I can only see `mysql: [Warning] Using a password on the command line interface can be insecure.` 

The `/tmp/test.mysql` file shows me that dadbod only executes `-h mysql -P 3306 -u user -ppassword database -t`.

When I execute `mysql -h mysql -P 3306 -u user -ppassword database -e "select * from table"` manualy from my terminal this works without problems.

Do you have an idea how I can make it work with my `mysql` script setup?

**Comment by tpope** [comment]
Dadbod's mysql adapter only uses `-e` for `show tables` and `show databases` which power tab completion. For arbitrary command execution, it writes the query to stdin. You probably want `docker exec -i` to keep stdin open, but I am no Docker expert.
