### ISSUE TITLE
Add BigQuery adapter

### ISSUE THREAD

**Issue by LuisCebrian** [tpope/vim-dadbod#95]
Dear Tpope,

I'd like to be able to use dadbod with BigQuery. Any chance we could add the BigQuery adapter to the plugin?
To make things easier, the adapter could rely in the `bq` command installed with the [google sdk](https://cloud.google.com/sdk/docs/install).

Thanks a lot in advance. Your work is awesome!

**Comment by tpope** [comment]
User contributed adapters welcome. Creating an adapter is fairly accessible: Pick a similar existing adapter, copy, paste, and tweak.
