### ISSUE TITLE
Pass extra CA certs param in URL to mongo client

### ISSUE THREAD

**Issue by opensourcegeek** [tpope/vim-dadbod#96]
Thanks for this plugin, I use this for postgres and it's really neat to not having to reach out for pgadmin - I'm now working with mongo as well and wanted to give this plugin a try. It works fine locally but when trying to connect to AWS document db it failed with `ssl peer certificate validation failed`.  I've to pass in extra CA certs file

Following is the URL I'm using, 

```
mongodb://USER:PASS@HOST:27017/?ssl=true&ssl_ca_certs=/path/to/rds-combined-ca-bundle.pem
```

Running the same through `mongo` client directly works fine. I had a quick skim through the code to see if I can figure out if extra CA certs params are passed through, but I'm not sure if it's passing through extra params that this plugin is not aware of or if it quiety drops them. Does the plugin pass this extra params to mongo client?

**Comment by tpope** [comment]
If there are unrecognized query params, the URL is passed directly to `mongo`. You can confirm what command is running with the following incantation:

```
:echo db#adapter#mongodb#interactive('mongodb://USER:PASS@HOST:27017/?ssl=true&ssl_ca_certs=/path/to/rds-combined-ca-bundle.pem')
['mongo', 'mongodb://USER:PASS@HOST:27017/?ssl=true&ssl_ca_certs=/path/to/rds-combined-ca-bundle.pem']
```

**Comment by opensourcegeek** [comment]
Cheers @tpope - the extra params are getting passed through, I'd have to check why it's still not working though but at least I know I can take this plugin out of the equation. Thanks
